export const ROUTES = {
  LOG_IN: '/login',
  SIGN_UP: '/signup',
  AUTHORIZATION: '/',
  PROFILE: '/profile',
  HOME: '/home',
  EXPLORE: '/explore',
  NOTIFICATIONS: '/notifications',
  MESSAGES: '/messages',
  BOOKMARKS: '/bookmarks',
  LISTS: '/lists',
  MORE: '/more',
  USERS: '/users/',
  TWEETS: '/tweets/',
} as const;

export const CONSTANTS = {
  ASIDE_TWEET: 'Tweet',
  ASIDE_LOG_OUT: 'Log out',
  PROFILE_BTN: 'Edit profile',
  EDIT_BTN: 'Save',
  EDIT_TITLE: 'Edit profile',
  HOME_TITLE: 'Home',
  SEARCH_TITLE: 'Search results',
  SEARCH_PLACEHOLDER_USERS: 'Search Users',
  SEARCH_PLACEHOLDER_TWITTER: 'Search Twitter',
  AUTH_TITLE: 'Happening now',
  AUTH_SUBTITLE: 'Join Twitter today',
  AUTH_LOGIN_TEXT: 'Already have an account? ',
  AUTH_GOOGLE: 'Sign up with Google',
  AUTH_EMAIL: 'Sign up with email',
  AUTH_LOG_IN: 'Log in',
  SIGN_UP_TITLE: 'Create an account',
  SIGN_UP_SUBTITLE: 'Date of birth',
  SIGN_UP_TEXT_DATE:
    'Facilisi sem pulvinar velit nunc, gravida scelerisque amet nibh sit. Quis bibendum ante phasellus metus, magna lacinia sed augue. Odio enim nascetur leo mauris vel eget. Pretium id ullamcorper blandit viverra dignissim eget tellus. Nibh mi massa in molestie a sit. Elit congue.',
  SIGN_UP_EMAIL_LINK: 'User email',
  SIGN_UP_BTN: 'Next',
  LOG_IN_TITLE: 'Log in to Twitter',
  LOG_IN_BTN: ' Log in',
  LOGIN_IN_SIGN_UP_LINK: 'Sign up to Twitter',
} as const;

export const FOOTER_AUTH = [
  'About',
  'Help Center',
  'Terms of Service',
  'Privacy Policy',
  'Cookie Policy',
  'Ads info',
  'Blog',
  'Status',
  'Carrres',
  'Brand Resources',
  'Advertsing',
  'Marketing',
  'Twitter for Business',
  'Developers',
  'Directory',
  'Settings',
  '© 2021 Twitter, Inc.',
] as const;
