import { Input as InputApp } from './Input';
import { Button as ButtonApp } from './Button';
import { AuthLink as AuthLinkApp } from './AuthLink';
import { ErrorMessage as ErrorMessageApp } from './ErrorMessage';
import { IconTwitter as IconTwitterApp } from './IconTwitter';
import { UserTitle as UserTitleApp } from './UserTitle';
import { UserSubtitle as UserSubtitleApp } from './UserSubtitle';
import { UserInfo as UserInfoApp } from './UserInfo';
import { ImageUser as ImageUserApp } from './ImageUser';
import { Image } from './Image';

export const ErrorMessage = ErrorMessageApp;
export const AuthLink = AuthLinkApp;
export const Input = InputApp;
export const Button = ButtonApp;
export const IconTwitter = IconTwitterApp;
export const UserTitle = UserTitleApp;
export const UserSubtitle = UserSubtitleApp;
export const UserInfo = UserInfoApp;
export const ImageUser = ImageUserApp;
export const ImageApp = Image;
